server:
  port: 8080
  servlet:
    context-path: /shop

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_db
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Vuzdapoet1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 

jwt:
  signerKey: "/X80Trc/zPkE38VMU0U2SyEVUuMfnLcGyDY2Y2/UdGxU+dn4/iDAr3lfUW6t9cNM\r\n"
  valid-duration: 3600 #in second
  refreshable-duration: 360000 #in second